REGISTER_USER = 'REGISTER'
CREATE_CHAT = 'CREATE_CHAT'
ADD_USER_TO_CHAT = 'ADD_TO_CHAT'
SEND_MESSAGE = 'SEND_MESSAGE'
LIST_USERS = 'LIST_USERS'
LIST_MY_CHATS = 'MY_CHATS'
LIST_USERS_IN_CHAT = 'CHAT_MEMBERS'
LIST_MESSAGES_IN_CHAT = 'LIST_MESSAGES'


